apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  labels:
    app: gloo
    app.kubernetes.io/managed-by: Helm
    gloo: oss-rate-limit
  name: oss-rate-limit
  namespace: gloo-system
spec:
  healthChecks:
  - grpcHealthCheck:
      serviceName: ratelimit
    healthyThreshold: 5
    interval: 60s
    timeout: 5s
    unhealthyThreshold: 5
  kube:
    serviceName: oss-rate-limit
    serviceNamespace: gloo-system
    servicePort: 18081
    serviceSpec:
      grpc: {}

