apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: gloo
    meta.helm.sh/release-namespace: gloo-system
  creationTimestamp: "2022-05-10T09:29:05Z"
  labels:
    app: gloo
    app.kubernetes.io/managed-by: Helm
    gloo: oss-rate-limit
  name: oss-rate-limit
  namespace: gloo-system
  resourceVersion: "1852"
  uid: d02d9302-a188-486f-aeaf-e9517c5fc81f
secrets:
  - name: rate-limit-token-nwl8h
